version: 2

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/node:10.6.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d3:6f:81:ba:5c:81:2b:0b:2d:bd:a8:0a:98:94:0f:98"
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "presentation/package.json" }}
      - run:
          name: "Installing dependencies"
          command: cd presentation && yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "presentation/package.json" }}
          paths:
            - presentation/node_modules
      - run:
          name: "Building project"
          command: cd presentation && yarn build
      - run:
          name: "Deploying distribution"
          command: ./.circleci/deploy.sh
