CREATE TABLE NOTE (
  ID      BIGSERIAL     PRIMARY KEY,
  CONTENT VARCHAR(128)  NOT NULL,
  IS_DONE BOOLEAN       NOT NULL,
);

INSERT INTO NOTE VALUES (1, 'Write Code', FALSE);
INSERT INTO NOTE VALUES (2, 'Test Code', FALSE);
INSERT INTO NOTE VALUES (3, 'Ship Code', FALSE);

CREATE SEQUENCE hibernate_sequence START 4;